export interface TerminalColors {
  background: string;
  foreground: string;
  cursor: string;
  selectionBackground: string;
  black: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  magenta: string;
  cyan: string;
  white: string;
}

export interface Theme {
  name: string;
  label: string;
  light?: boolean;
  colors: Record<string, string>;
  terminal: TerminalColors;
}

// Event system for theme changes
type ThemeListener = (theme: Theme) => void;
const listeners: Set<ThemeListener> = new Set();

export function onThemeChange(fn: ThemeListener): () => void {
  listeners.add(fn);
  return () => { listeners.delete(fn); };
}

export const themes: Theme[] = [
  // ─── Dark Themes ───
  {
    name: "tokyonight",
    label: "Tokyo Night",
    colors: {
      "--bg-primary": "#1a1b26",
      "--bg-secondary": "#16161e",
      "--bg-hover": "#292e42",
      "--bg-elevated": "#1f2335",
      "--text-primary": "#a9b1d6",
      "--text-secondary": "#787c99",
      "--text-tertiary": "#565a6e",
      "--accent-blue": "#7aa2f7",
      "--accent-green": "#9ece6a",
      "--accent-red": "#f7768e",
      "--accent-cyan": "#7dcfff",
      "--accent-yellow": "#e0af68",
      "--accent-purple": "#bb9af7",
      "--border": "#292e42",
      "--border-subtle": "#1f2335",
      "--scrollbar-thumb": "#292e42",
      "--scrollbar-track": "#1a1b26",
    },
    terminal: {
      background: "#1a1b26",
      foreground: "#a9b1d6",
      cursor: "#c0caf5",
      selectionBackground: "#33467c",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
    },
  },
  {
    name: "catppuccin",
    label: "Catppuccin Mocha",
    colors: {
      "--bg-primary": "#1e1e2e",
      "--bg-secondary": "#181825",
      "--bg-hover": "#313244",
      "--bg-elevated": "#24243b",
      "--text-primary": "#cdd6f4",
      "--text-secondary": "#a6adc8",
      "--text-tertiary": "#6c7086",
      "--accent-blue": "#89b4fa",
      "--accent-green": "#a6e3a1",
      "--accent-red": "#f38ba8",
      "--accent-cyan": "#94e2d5",
      "--accent-yellow": "#f9e2af",
      "--accent-purple": "#cba6f7",
      "--border": "#313244",
      "--border-subtle": "#24243b",
      "--scrollbar-thumb": "#313244",
      "--scrollbar-track": "#1e1e2e",
    },
    terminal: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      selectionBackground: "#45475a",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#cba6f7",
      cyan: "#94e2d5",
      white: "#bac2de",
    },
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: {
      "--bg-primary": "#282a36",
      "--bg-secondary": "#1e1f29",
      "--bg-hover": "#44475a",
      "--bg-elevated": "#2d2f3d",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#6272a4",
      "--text-tertiary": "#4a5578",
      "--accent-blue": "#8be9fd",
      "--accent-green": "#50fa7b",
      "--accent-red": "#ff5555",
      "--accent-cyan": "#8be9fd",
      "--accent-yellow": "#f1fa8c",
      "--accent-purple": "#bd93f9",
      "--border": "#44475a",
      "--border-subtle": "#2d2f3d",
      "--scrollbar-thumb": "#44475a",
      "--scrollbar-track": "#282a36",
    },
    terminal: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      selectionBackground: "#44475a",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
    },
  },
  {
    name: "nord",
    label: "Nord",
    colors: {
      "--bg-primary": "#2e3440",
      "--bg-secondary": "#272c36",
      "--bg-hover": "#434c5e",
      "--bg-elevated": "#3b4252",
      "--text-primary": "#eceff4",
      "--text-secondary": "#d8dee9",
      "--text-tertiary": "#7b88a1",
      "--accent-blue": "#88c0d0",
      "--accent-green": "#a3be8c",
      "--accent-red": "#bf616a",
      "--accent-cyan": "#8fbcbb",
      "--accent-yellow": "#ebcb8b",
      "--accent-purple": "#b48ead",
      "--border": "#4c566a",
      "--border-subtle": "#3b4252",
      "--scrollbar-thumb": "#4c566a",
      "--scrollbar-track": "#2e3440",
    },
    terminal: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      selectionBackground: "#434c5e",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
    },
  },
  {
    name: "onedark",
    label: "One Dark",
    colors: {
      "--bg-primary": "#282c34",
      "--bg-secondary": "#21252b",
      "--bg-hover": "#2c313c",
      "--bg-elevated": "#2d323b",
      "--text-primary": "#abb2bf",
      "--text-secondary": "#7f848e",
      "--text-tertiary": "#5c6370",
      "--accent-blue": "#61afef",
      "--accent-green": "#98c379",
      "--accent-red": "#e06c75",
      "--accent-cyan": "#56b6c2",
      "--accent-yellow": "#e5c07b",
      "--accent-purple": "#c678dd",
      "--border": "#3e4451",
      "--border-subtle": "#2c313c",
      "--scrollbar-thumb": "#3e4451",
      "--scrollbar-track": "#282c34",
    },
    terminal: {
      background: "#282c34",
      foreground: "#abb2bf",
      cursor: "#528bff",
      selectionBackground: "#3e4451",
      black: "#5c6370",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
    },
  },
  {
    name: "gruvbox",
    label: "Gruvbox Dark",
    colors: {
      "--bg-primary": "#282828",
      "--bg-secondary": "#1d2021",
      "--bg-hover": "#3c3836",
      "--bg-elevated": "#32302f",
      "--text-primary": "#ebdbb2",
      "--text-secondary": "#a89984",
      "--text-tertiary": "#7c6f64",
      "--accent-blue": "#83a598",
      "--accent-green": "#b8bb26",
      "--accent-red": "#fb4934",
      "--accent-cyan": "#8ec07c",
      "--accent-yellow": "#fabd2f",
      "--accent-purple": "#d3869b",
      "--border": "#504945",
      "--border-subtle": "#3c3836",
      "--scrollbar-thumb": "#504945",
      "--scrollbar-track": "#282828",
    },
    terminal: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      selectionBackground: "#504945",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
    },
  },
  {
    name: "solarized",
    label: "Solarized Dark",
    colors: {
      "--bg-primary": "#002b36",
      "--bg-secondary": "#00212b",
      "--bg-hover": "#073642",
      "--bg-elevated": "#003847",
      "--text-primary": "#839496",
      "--text-secondary": "#657b83",
      "--text-tertiary": "#586e75",
      "--accent-blue": "#268bd2",
      "--accent-green": "#859900",
      "--accent-red": "#dc322f",
      "--accent-cyan": "#2aa198",
      "--accent-yellow": "#b58900",
      "--accent-purple": "#6c71c4",
      "--border": "#073642",
      "--border-subtle": "#003847",
      "--scrollbar-thumb": "#073642",
      "--scrollbar-track": "#002b36",
    },
    terminal: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#839496",
      selectionBackground: "#073642",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
    },
  },
  {
    name: "rosepine",
    label: "Rose Pine",
    colors: {
      "--bg-primary": "#191724",
      "--bg-secondary": "#1f1d2e",
      "--bg-hover": "#26233a",
      "--bg-elevated": "#1f1d2e",
      "--text-primary": "#e0def4",
      "--text-secondary": "#908caa",
      "--text-tertiary": "#6e6a86",
      "--accent-blue": "#31748f",
      "--accent-green": "#9ccfd8",
      "--accent-red": "#eb6f92",
      "--accent-cyan": "#9ccfd8",
      "--accent-yellow": "#f6c177",
      "--accent-purple": "#c4a7e7",
      "--border": "#26233a",
      "--border-subtle": "#1f1d2e",
      "--scrollbar-thumb": "#26233a",
      "--scrollbar-track": "#191724",
    },
    terminal: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#524f67",
      selectionBackground: "#26233a",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
    },
  },
  {
    name: "kanagawa",
    label: "Kanagawa",
    colors: {
      "--bg-primary": "#1f1f28",
      "--bg-secondary": "#16161d",
      "--bg-hover": "#2a2a37",
      "--bg-elevated": "#223249",
      "--text-primary": "#dcd7ba",
      "--text-secondary": "#727169",
      "--text-tertiary": "#54546d",
      "--accent-blue": "#7e9cd8",
      "--accent-green": "#76946a",
      "--accent-red": "#c34043",
      "--accent-cyan": "#7fb4ca",
      "--accent-yellow": "#e6c384",
      "--accent-purple": "#957fb8",
      "--border": "#2a2a37",
      "--border-subtle": "#223249",
      "--scrollbar-thumb": "#2a2a37",
      "--scrollbar-track": "#1f1f28",
    },
    terminal: {
      background: "#1f1f28",
      foreground: "#dcd7ba",
      cursor: "#c8c093",
      selectionBackground: "#2d4f67",
      black: "#16161d",
      red: "#c34043",
      green: "#76946a",
      yellow: "#c0a36e",
      blue: "#7e9cd8",
      magenta: "#957fb8",
      cyan: "#6a9589",
      white: "#c8c093",
    },
  },
  {
    name: "github-dark",
    label: "GitHub Dark",
    colors: {
      "--bg-primary": "#0d1117",
      "--bg-secondary": "#010409",
      "--bg-hover": "#161b22",
      "--bg-elevated": "#161b22",
      "--text-primary": "#e6edf3",
      "--text-secondary": "#8b949e",
      "--text-tertiary": "#484f58",
      "--accent-blue": "#58a6ff",
      "--accent-green": "#3fb950",
      "--accent-red": "#f85149",
      "--accent-cyan": "#79c0ff",
      "--accent-yellow": "#d29922",
      "--accent-purple": "#bc8cff",
      "--border": "#30363d",
      "--border-subtle": "#21262d",
      "--scrollbar-thumb": "#30363d",
      "--scrollbar-track": "#0d1117",
    },
    terminal: {
      background: "#0d1117",
      foreground: "#e6edf3",
      cursor: "#e6edf3",
      selectionBackground: "#264f78",
      black: "#484f58",
      red: "#ff7b72",
      green: "#3fb950",
      yellow: "#d29922",
      blue: "#58a6ff",
      magenta: "#bc8cff",
      cyan: "#79c0ff",
      white: "#e6edf3",
    },
  },
  // ─── Light Themes ───
  {
    name: "tokyonight-light",
    label: "Tokyo Night Light",
    light: true,
    colors: {
      "--bg-primary": "#e1e2e7",
      "--bg-secondary": "#d5d6db",
      "--bg-hover": "#c8c9d0",
      "--bg-elevated": "#cbccd3",
      "--text-primary": "#343b58",
      "--text-secondary": "#5a607a",
      "--text-tertiary": "#8990a7",
      "--accent-blue": "#2e7de9",
      "--accent-green": "#587539",
      "--accent-red": "#f52a65",
      "--accent-cyan": "#007197",
      "--accent-yellow": "#8c6c3e",
      "--accent-purple": "#9854f1",
      "--border": "#b9bac4",
      "--border-subtle": "#d0d1d8",
      "--scrollbar-thumb": "#aeb0b9",
      "--scrollbar-track": "#e1e2e7",
    },
    terminal: {
      background: "#e1e2e7",
      foreground: "#343b58",
      cursor: "#343b58",
      selectionBackground: "#b6bfe2",
      black: "#0f0f14",
      red: "#f52a65",
      green: "#587539",
      yellow: "#8c6c3e",
      blue: "#2e7de9",
      magenta: "#9854f1",
      cyan: "#007197",
      white: "#6172b0",
    },
  },
  {
    name: "catppuccin-latte",
    label: "Catppuccin Latte",
    light: true,
    colors: {
      "--bg-primary": "#eff1f5",
      "--bg-secondary": "#e6e9ef",
      "--bg-hover": "#d4d8e3",
      "--bg-elevated": "#dce0e8",
      "--text-primary": "#4c4f69",
      "--text-secondary": "#6c6f85",
      "--text-tertiary": "#9ca0b0",
      "--accent-blue": "#1e66f5",
      "--accent-green": "#40a02b",
      "--accent-red": "#d20f39",
      "--accent-cyan": "#179299",
      "--accent-yellow": "#df8e1d",
      "--accent-purple": "#8839ef",
      "--border": "#bcc0cc",
      "--border-subtle": "#ccd0da",
      "--scrollbar-thumb": "#acb0be",
      "--scrollbar-track": "#eff1f5",
    },
    terminal: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      selectionBackground: "#ccd0da",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#8839ef",
      cyan: "#179299",
      white: "#acb0be",
    },
  },
  {
    name: "github-light",
    label: "GitHub Light",
    light: true,
    colors: {
      "--bg-primary": "#ffffff",
      "--bg-secondary": "#f0f2f5",
      "--bg-hover": "#e2e6ea",
      "--bg-elevated": "#e8ecf0",
      "--text-primary": "#1f2328",
      "--text-secondary": "#656d76",
      "--text-tertiary": "#8b949e",
      "--accent-blue": "#0969da",
      "--accent-green": "#1a7f37",
      "--accent-red": "#cf222e",
      "--accent-cyan": "#0550ae",
      "--accent-yellow": "#9a6700",
      "--accent-purple": "#8250df",
      "--border": "#d0d7de",
      "--border-subtle": "#e1e5e9",
      "--scrollbar-thumb": "#b8bfc7",
      "--scrollbar-track": "#ffffff",
    },
    terminal: {
      background: "#ffffff",
      foreground: "#1f2328",
      cursor: "#1f2328",
      selectionBackground: "#dbe9f9",
      black: "#24292f",
      red: "#cf222e",
      green: "#116329",
      yellow: "#9a6700",
      blue: "#0969da",
      magenta: "#8250df",
      cyan: "#0550ae",
      white: "#6e7781",
    },
  },
  {
    name: "solarized-light",
    label: "Solarized Light",
    light: true,
    colors: {
      "--bg-primary": "#fdf6e3",
      "--bg-secondary": "#eee8d5",
      "--bg-hover": "#ddd6c1",
      "--bg-elevated": "#e4ddca",
      "--text-primary": "#586e75",
      "--text-secondary": "#657b83",
      "--text-tertiary": "#93a1a1",
      "--accent-blue": "#268bd2",
      "--accent-green": "#859900",
      "--accent-red": "#dc322f",
      "--accent-cyan": "#2aa198",
      "--accent-yellow": "#b58900",
      "--accent-purple": "#6c71c4",
      "--border": "#d3cbb7",
      "--border-subtle": "#e0d8c4",
      "--scrollbar-thumb": "#c9c1ad",
      "--scrollbar-track": "#fdf6e3",
    },
    terminal: {
      background: "#fdf6e3",
      foreground: "#586e75",
      cursor: "#586e75",
      selectionBackground: "#eee8d5",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
    },
  },
];

const STORAGE_KEY = "proximus-theme";

export function getTheme(name: string): Theme | undefined {
  return themes.find((t) => t.name === name);
}

export function applyTheme(themeName: string): void {
  const theme = themes.find((t) => t.name === themeName);
  if (!theme) return;

  const root = document.documentElement;
  for (const [key, value] of Object.entries(theme.colors)) {
    root.style.setProperty(key, value);
  }
  localStorage.setItem(STORAGE_KEY, themeName);

  // Notify listeners (terminal, etc.)
  listeners.forEach((fn) => fn(theme));
}

export function getSavedTheme(): string {
  return localStorage.getItem(STORAGE_KEY) || "tokyonight";
}

export function loadSavedTheme(): void {
  applyTheme(getSavedTheme());
}
